const data = {
  code: 1,
  data: [
    {
      gameList: [
        {
          area: 4,
          channelId: 50,
          descript: 'PM体育',
          endDate: null,
          gameId: 50,
          gameType: 2,
          icon: {
            dark: { mode: 2, path: '/api/forehead/system/file/get/643bc7708491c821eaa7c5fd.png' },
            light: { mode: 2, path: '/api/forehead/system/file/get/643bc7727adc213d08adfcbb.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 50,
          name: 'PM体育',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/643bc7727adc213d08adfcbb.png',
          position: 3,
          recommendType: 3,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 0,
          subGameNum: 1,
          walletName: 'PM体育'
        },
        {
          area: 4,
          channelId: 45,
          descript: 'FB体育',
          endDate: null,
          gameId: 45,
          gameType: 2,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/6438ca2b57d7e31a93967ab0.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/6438ca292890874bd720d39c.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 45,
          name: 'FB体育',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6438ca292890874bd720d39c.png',
          position: 4,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 0,
          subGameNum: 1,
          walletName: 'FB体育'
        },
        {
          area: 4,
          channelId: 31,
          descript: 'IM体育',
          endDate: null,
          gameId: 31,
          gameType: 2,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/6438c3a8776dfb6c498dcccd.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/6438c3a6e1a33852aa59776c.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 31,
          name: 'IM体育',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6438c3a6e1a33852aa59776c.png',
          position: 3,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 0,
          subGameNum: 1,
          walletName: 'IM体育'
        }
      ],
      gameType: 2,
      icon: {
        dark: '/api/forehead/system/file/get/null',
        light: '/api/forehead/system/file/get/642519cb9cb8ba76cb7d6904.png'
      },
      iconSelected: {
        dark: '/api/forehead/system/file/get/null',
        light: '/api/forehead/system/file/get/642519b7e827c3768206691d.png'
      },
      name: '体育',
      type: 'sport'
    },
    {
      gameList: [
        {
          area: 4,
          channelId: 1,
          descript: 'AG',
          endDate: null,
          gameId: 1,
          gameType: 1,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/6450d8a95cbc117df01a5d80.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/6450d8a8bceb742b5a011bb3.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 1,
          name: 'AG真人',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6450d8a8bceb742b5a011bb3.png',
          position: 1,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 0,
          subGameNum: 1,
          walletName: 'AG'
        },
        {
          area: 4,
          channelId: 46,
          descript: 'PM真人',
          endDate: null,
          gameId: 46,
          gameType: 1,
          icon: {
            dark: { mode: 2, path: '/api/forehead/system/file/get/6450d8c2654f9a77bfaa8a4b.png' },
            light: { mode: 2, path: '/api/forehead/system/file/get/6450d8c1c6add805a0b61639.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 46,
          name: 'PM真人',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6450d8c1c6add805a0b61639.png',
          position: 2,
          recommendType: 3,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 0,
          subGameNum: 1,
          walletName: 'PM真人'
        },
        {
          area: 4,
          channelId: 30,
          descript: 'BG',
          endDate: null,
          gameId: 30,
          gameType: 1,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/6438c1bbe1a33852aa597749.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/6438c1b9d14dfc54668c5415.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 30,
          name: 'BG真人',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6438c1b9d14dfc54668c5415.png',
          position: 3,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 0,
          subGameNum: 1,
          walletName: 'BG'
        },
        {
          area: 4,
          channelId: 55,
          descript: 'DG真人',
          endDate: null,
          gameId: 55,
          gameType: 1,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/6438cca0e1a33852aa59782f.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/6438cc9ed14dfc54668c54eb.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 55,
          name: 'DG真人',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6438cc9ed14dfc54668c54eb.png',
          position: 4,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 0,
          subGameNum: 1,
          walletName: 'DG真人'
        },
        {
          area: 4,
          channelId: 58,
          descript: 'WM真人',
          endDate: null,
          gameId: 58,
          gameType: 1,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/6438cd42776dfb6c498dcdd6.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/6438cd40e1a33852aa59786e.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 58,
          name: 'WM真人',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6438cd40e1a33852aa59786e.png',
          position: 6,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 0,
          subGameNum: 1,
          walletName: 'WM真人'
        },
        {
          area: 4,
          channelId: 60,
          descript: 'BBIN',
          endDate: null,
          gameId: 60,
          gameType: 1,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/6438cdd957d7e31a93967b2e.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/6438cdd72890874bd720d41e.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 60,
          name: 'BBIN真人',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6438cdd72890874bd720d41e.png',
          position: 5,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 0,
          subGameNum: 1,
          walletName: 'BBIN'
        },
        {
          area: 4,
          channelId: 56,
          descript: 'AE真人',
          endDate: null,
          gameId: 56,
          gameType: 1,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/6438ccd69ddac5660db2ec05.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/6438ccd4776dfb6c498dcd9a.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 56,
          name: 'AE真人',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6438ccd4776dfb6c498dcd9a.png',
          position: 7,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 0,
          subGameNum: 1,
          walletName: 'AE真人'
        }
      ],
      gameType: 1,
      icon: {
        dark: '/api/forehead/system/file/get/null',
        light: '/api/forehead/system/file/get/64251a8c43417d05dc121d2b.png'
      },
      iconSelected: {
        dark: '/api/forehead/system/file/get/null',
        light: '/api/forehead/system/file/get/64251a7e0fe07d2b2518756d.png'
      },
      name: '真人',
      type: 'real'
    },
    {
      gameList: [
        {
          area: 4,
          channelId: 39,
          descript: 'B棋牌',
          endDate: null,
          gameId: 39,
          gameType: 6,
          icon: {
            dark: { mode: 2, path: '/api/forehead/system/file/get/6438c82f8405775c12ea03dc.png' },
            light: { mode: 2, path: '/api/forehead/system/file/get/6438c82c1404a147e171faab.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 39,
          name: 'B棋牌',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6438c82c1404a147e171faab.png',
          position: 1,
          recommendType: 3,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 0,
          subGameNum: 1,
          walletName: 'B棋牌'
        },
        {
          area: 4,
          channelId: 9,
          descript: '开元棋牌',
          endDate: null,
          gameId: 9,
          gameType: 6,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/6438c0d5d14dfc54668c5402.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/6438c0dae1a33852aa597736.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 9,
          name: '开元棋牌',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6438c0dae1a33852aa597736.png',
          position: 2,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 0,
          subGameNum: 1,
          walletName: '开元棋牌'
        },
        {
          area: 4,
          channelId: 47,
          descript: 'PM棋牌',
          endDate: null,
          gameId: 47,
          gameType: 6,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/6438cacd2890874bd720d3a9.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/6438cabe8405775c12ea040c.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 47,
          name: 'PM棋牌',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6438cabe8405775c12ea040c.png',
          position: 3,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 0,
          subGameNum: 1,
          walletName: 'PM棋牌'
        },
        {
          area: 4,
          channelId: 54,
          descript: '博乐棋牌',
          endDate: 1684036800999,
          gameId: 54,
          gameType: 6,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/6438cc5b04434c28280075a8.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/6438cc5857d7e31a93967ad8.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 54,
          name: 'BL棋牌',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6438cc5857d7e31a93967ad8.png',
          position: 4,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: 1683876900000,
          status: 1,
          subGame: 0,
          subGameNum: 1,
          walletName: '博乐棋牌'
        },
        {
          area: 4,
          channelId: 42,
          descript: '双赢棋牌',
          endDate: null,
          gameId: 42,
          gameType: 6,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/6438c937776dfb6c498dcd4f.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/6438c934d14dfc54668c54ab.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 42,
          name: '双赢棋牌',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6438c934d14dfc54668c54ab.png',
          position: 5,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 0,
          subGameNum: 1,
          walletName: '双赢棋牌'
        },
        {
          area: 4,
          channelId: 68,
          descript: 'M棋牌',
          endDate: null,
          gameId: 68,
          gameType: 6,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/6438db58e1a33852aa5978e9.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/6438db54d14dfc54668c55a9.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 68,
          name: 'M棋牌',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6438db54d14dfc54668c55a9.png',
          position: 7,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 0,
          subGameNum: 1,
          walletName: 'M棋牌'
        },
        {
          area: 4,
          channelId: 53,
          descript: 'V8棋牌',
          endDate: null,
          gameId: 53,
          gameType: 6,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/6438cc2e2890874bd720d3c2.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/6438cc2c8405775c12ea0429.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 53,
          name: 'V8棋牌',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6438cc2c8405775c12ea0429.png',
          position: 6,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 0,
          subGameNum: 1,
          walletName: 'V8棋牌'
        }
      ],
      gameType: 6,
      icon: {
        dark: '/api/forehead/system/file/get/null',
        light: '/api/forehead/system/file/get/6425196d386c0a2aa7716166.png'
      },
      iconSelected: {
        dark: '/api/forehead/system/file/get/null',
        light: '/api/forehead/system/file/get/6425198030095c7e8c8a3e22.png'
      },
      name: '棋牌',
      type: 'poker'
    },
    {
      gameList: [
        {
          area: 4,
          channelId: 51,
          descript: 'KS捕鱼',
          endDate: null,
          gameId: 51,
          gameType: 4,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/6438cbaed14dfc54668c54dd.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/6438cbad04434c282800759d.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 51,
          name: 'KS捕鱼',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6438cbad04434c282800759d.png',
          position: 1,
          recommendType: 3,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 0,
          subGameNum: 1,
          walletName: 'KS捕鱼'
        },
        {
          area: 4,
          channelId: 35,
          descript: 'PM捕鱼',
          endDate: null,
          gameId: 35,
          gameType: 4,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/6438c3fc2890874bd720d314.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/6438c3fb8405775c12ea037b.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 35,
          name: 'PM捕鱼',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6438c3fb8405775c12ea037b.png',
          position: 6,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 0,
          subGameNum: 1,
          walletName: 'PM捕鱼'
        },
        {
          area: 4,
          channelId: 1,
          descript: 'AG',
          endDate: null,
          gameId: 2,
          gameType: 4,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/6438c023e1a33852aa597729.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/6438c021d14dfc54668c53f5.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 2,
          name: 'AG捕鱼',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6438c021d14dfc54668c53f5.png',
          position: 2,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 0,
          subGameNum: 1,
          walletName: 'AG'
        },
        {
          area: 4,
          channelId: 60,
          descript: 'BBIN',
          endDate: null,
          gameId: 65,
          gameType: 4,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/6438db0657d7e31a93967b93.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/6438db032890874bd720d481.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 65,
          name: 'BBIN捕鱼',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6438db032890874bd720d481.png',
          position: 9,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 0,
          subGameNum: 1,
          walletName: 'BBIN'
        },
        {
          area: 4,
          channelId: 38,
          descript: 'PG电子',
          endDate: null,
          gameId: 38001,
          gameType: 3,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/6438c57e776dfb6c498dcd0d.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/6438c57ce1a33852aa5977ae.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 38,
          name: 'PG电子',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6438c57ce1a33852aa5977ae.png',
          position: 3,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 1,
          subGameNum: 577,
          walletName: 'PG电子'
        },
        {
          area: 4,
          channelId: 57,
          descript: 'CQ9电子',
          endDate: null,
          gameId: 57001,
          gameType: 3,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/6438cd1ad14dfc54668c5510.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/6438cd1804434c28280075d0.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 57,
          name: 'CQ9电子',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6438cd1804434c28280075d0.png',
          position: 5,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 1,
          subGameNum: 1179,
          walletName: 'CQ9电子'
        },
        {
          area: 4,
          channelId: 1,
          descript: 'AG',
          endDate: null,
          gameId: 202,
          gameType: 3,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/6438c0999ddac5660db2eb10.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/6438c096776dfb6c498dcc98.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 6,
          name: 'AG电子',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6438c096776dfb6c498dcc98.png',
          position: 4,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 1,
          subGameNum: 853,
          walletName: 'AG'
        },
        {
          area: 4,
          channelId: 36,
          descript: 'PM电子',
          endDate: null,
          gameId: 36001,
          gameType: 3,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/6438c431d14dfc54668c5447.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/6438c433e1a33852aa597782.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 36,
          name: 'PM电子',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6438c433e1a33852aa597782.png',
          position: 7,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 1,
          subGameNum: 204,
          walletName: 'PM电子'
        },
        {
          area: 4,
          channelId: 64,
          descript: 'CC88电子',
          endDate: null,
          gameId: 64001,
          gameType: 3,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/6438dae2e1a33852aa5978e2.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/6438dae0d14dfc54668c55a3.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 64,
          name: 'CC88电子',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6438dae0d14dfc54668c55a3.png',
          position: 10,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 1,
          subGameNum: 728,
          walletName: 'CC88电子'
        },
        {
          area: 4,
          channelId: 60,
          descript: 'BBIN',
          endDate: null,
          gameId: 59005,
          gameType: 3,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/6438cd9e57d7e31a93967b29.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/6438cd9c2890874bd720d419.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 59,
          name: 'BBIN电子',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6438cd9c2890874bd720d419.png',
          position: 8,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 1,
          subGameNum: 1190,
          walletName: 'BBIN'
        }
      ],
      gameType: 3,
      icon: {
        dark: '/api/forehead/system/file/get/null',
        light: '/api/forehead/system/file/get/6425190f9cb8ba76cb7d68ef.png'
      },
      iconSelected: {
        dark: '/api/forehead/system/file/get/null',
        light: '/api/forehead/system/file/get/642519209cb8ba76cb7d68f3.png'
      },
      name: '电子',
      type: 'digital'
    },
    {
      gameList: [
        {
          area: 4,
          channelId: 28,
          descript: 'B彩票',
          endDate: null,
          gameId: 28,
          gameType: 0,
          icon: {
            dark: { mode: 2, path: '/api/forehead/system/file/get/643b62646155d21ccb061bf1.png' },
            light: { mode: 2, path: '/api/forehead/system/file/get/643b6265d7dd5c435a11c239.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 28,
          name: 'B彩票',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/643b6265d7dd5c435a11c239.png',
          position: 1,
          recommendType: 3,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 0,
          subGameNum: 1,
          walletName: 'B彩票'
        },
        {
          area: 4,
          channelId: 49,
          descript: 'PM彩票',
          endDate: null,
          gameId: 49,
          gameType: 0,
          icon: {
            dark: { mode: 2, path: '/api/forehead/system/file/get/643bc4498491c821eaa7c5f4.png' },
            light: { mode: 2, path: '/api/forehead/system/file/get/643bc446572adb0d91be92d8.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 49,
          name: 'PM彩票',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/643bc446572adb0d91be92d8.png',
          position: 2,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 0,
          subGameNum: 1,
          walletName: 'PM彩票'
        },
        {
          area: 4,
          channelId: 63,
          descript: 'Go彩票',
          endDate: null,
          gameId: 63,
          gameType: 0,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/6438dac11404a147e171fbb4.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/6438dabf9ddac5660db2ecb6.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 63,
          name: 'Go彩票',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6438dabf9ddac5660db2ecb6.png',
          position: 4,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 0,
          subGameNum: 1,
          walletName: 'Go彩票'
        },
        {
          area: 4,
          channelId: 60,
          descript: 'BBIN',
          endDate: null,
          gameId: 61,
          gameType: 0,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/6438da918405775c12ea04e1.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/6438da8f1404a147e171fbaf.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 61,
          name: 'BBIN彩票',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6438da8f1404a147e171fbaf.png',
          position: 3,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 0,
          subGameNum: 1,
          walletName: 'BBIN'
        },
        {
          area: 4,
          channelId: 41,
          descript: 'VR彩票',
          endDate: null,
          gameId: 41,
          gameType: 0,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/6438c7279ddac5660db2eba3.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/6438c725776dfb6c498dcd30.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 41,
          name: 'VR彩票',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6438c725776dfb6c498dcd30.png',
          position: 4,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 0,
          subGameNum: 1,
          walletName: 'VR彩票'
        },
        {
          area: 4,
          channelId: 52,
          descript: '天成彩票',
          endDate: null,
          gameId: 52,
          gameType: 0,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/6438cbe0776dfb6c498dcd89.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/6438cbdee1a33852aa597824.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 52,
          name: 'TCG彩票',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/6438cbdee1a33852aa597824.png',
          position: 5,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 0,
          subGameNum: 1,
          walletName: '天成彩票'
        }
      ],
      gameType: 0,
      icon: {
        dark: '/api/forehead/system/file/get/null',
        light: '/api/forehead/system/file/get/642510b79cb8ba76cb7d6898.png'
      },
      iconSelected: {
        dark: '/api/forehead/system/file/get/null',
        light: '/api/forehead/system/file/get/642510a743417d05dc121cb1.png'
      },
      name: '彩票',
      type: 'lottery'
    },
    {
      gameList: [
        {
          area: 4,
          channelId: 43,
          descript: 'IM电竞',
          endDate: null,
          gameId: 43,
          gameType: 5,
          icon: {
            dark: { mode: 2, path: '/api/forehead/system/file/get/643bc46593668015036155a6.png' },
            light: { mode: 2, path: '/api/forehead/system/file/get/643bc462bb72b740e781acc7.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 43,
          name: 'IM电竞',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/643bc462bb72b740e781acc7.png',
          position: 2,
          recommendType: 3,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 0,
          subGameNum: 1,
          walletName: 'IM电竞'
        },
        {
          area: 4,
          channelId: 48,
          descript: 'PM电竞',
          endDate: null,
          gameId: 48,
          gameType: 5,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/643ba637d7dd5c435a11fda8.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/643ba6356155d21ccb065773.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 48,
          name: 'PM电竞',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/643ba6356155d21ccb065773.png',
          position: 3,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 0,
          subGameNum: 1,
          walletName: 'PM电竞'
        },
        {
          area: 4,
          channelId: 26,
          descript: '泛亚电竞',
          endDate: null,
          gameId: 26,
          gameType: 5,
          icon: {
            dark: { mode: 1, path: '/api/forehead/system/file/get/643bad6f60ac0312e4aeb990.png' },
            light: { mode: 1, path: '/api/forehead/system/file/get/643bad6d99382d20bfda91e0.png' }
          },
          isCenterWallet: 0,
          link: '',
          maintenFlag: 0,
          maintenId: 26,
          name: '泛亚电竞',
          navGroup: '',
          picUrl: '/api/forehead/system/file/get/643bad6d99382d20bfda91e0.png',
          position: 1,
          recommendType: 0,
          shelfStatus: 1,
          showClient: 0,
          singleWallet: false,
          startDate: null,
          status: 0,
          subGame: 0,
          subGameNum: 1,
          walletName: '泛亚电竞'
        }
      ],
      gameType: 5,
      icon: {
        dark: '/api/forehead/system/file/get/null',
        light: '/api/forehead/system/file/get/64251a09554179456605a773.png'
      },
      iconSelected: {
        dark: '/api/forehead/system/file/get/null',
        light: '/api/forehead/system/file/get/64251a18966d18121dbc8e6c.png'
      },
      name: '电竞',
      type: 'gaming'
    }
  ],
  keyConfig: null,
  languagePassVal: null,
  message: 'SUCCESS'
}
export default data.data
